
services:
  db2:
    image: ibmcom/db2
    container_name: db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: admin123
      DBNAME: KOOPA
    ports:
      - "50000:50000"
    volumes:
      - db2_data:/database
    # (Opcional pero muy recomendado) healthcheck, DB2 tarda un rato en estar lista
    healthcheck:
      test: ["CMD-SHELL", "su - db2inst1 -c 'db2 connect to KOOPA' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10

  backend:
    build:
      context: ./koopa_backend
      dockerfile: Dockerfile
    container_name: koopa_backend
    depends_on:
      - db2
    working_dir: /app
    environment:
      ASPNETCORE_URLS: http://+:8080
      DB_CONNECTION: "Server=db2;Port=50000;Database=KOOPA;UID=db2inst1;PWD=admin123;"
      DOTNET_ENVIRONMENT: Development
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    ports:
      - "8080:8080"
    # volumen bind para detectar cambios en caliente
    volumes:
      - ./koopa_backend:/app
      # evitar que el bin/obj del contenedor pisen los tuyos
      - /app/bin
      - /app/obj
    command: ["dotnet", "watch", "run", "--urls", "http://+:8080"]

  
  frontend:
    build:
      context: ./koopa_frontend
      dockerfile: Dockerfile
    container_name: koopa_frontend
    working_dir: /app
    ports:
      - "3000:3000"

    develop:
      watch:
        - action: sync
          path: ./koopa_frontend
          target: /app
          ignore:
            - node_modules/
            - .next/

        # rebuild SOLO si cambian dependencias
        - action: rebuild
          path: ./koopa_frontend/package.json

    environment:
      NODE_ENV: development


  


volumes:
  db2_data:
